### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by DunklesKaltesNichts** [cosmocode/do#84] opened 2023-10-25 17:31 UTC
after i installed this plugin, this error message appears, when I uninstall it, the message is gone

SQLite: SQLSTATE[HY000]: General error: 1 near "DROP": syntax error

the plugins "struct" and "tagging" work without any problems. these also require sqlite.

manual installation
release 2023-04-04a "Jack Jackrum"

PHP Version 8.2.11
PDO Driver for SQLite 3.x  enabled
SQLite Library  3.27.2

**Comment by annda** [comment] 2023-10-26 12:03
I can't reproduce the error with a similar setup and a fresh manual install of do.

@DunklesKaltesNichts can you delete the database file (`data/meta/do.slite3`) and reinstall the plugin?

If the problem persists, please check the SQLite Interface (admin) and post the output from `Show database version` and `List tables`.

**Comment by DunklesKaltesNichts** [comment] 2023-10-26 20:24
deleting the database and reinstalling did not help.
Im uninstalling the plugin and looking for another solution.

![Screenshot_20231026-221919](https://github.com/cosmocode/do/assets/35750110/a1462134-808b-4674-adda-277b5c344a02)
![Screenshot_20231026-222043](https://github.com/cosmocode/do/assets/35750110/bc5779c6-d85d-4456-9f58-f5dca7340af5)

**Comment by rikfleuren** [comment] 2023-11-10 18:40
Got the same error on a system with SQLite version 3.7.17. Support for `ALTER TABLE DROP COLUMN`  was introduced in a later version: [https://sqlite.org/releaselog/3_35_0.html](https://sqlite.org/releaselog/3_35_0.html)

In `db/update0006.sql` the last statement fails: `ALTER TABLE tasks DROP msg;`. This file is probably meant to update the database to version 6 (latest version = 7). I am stuck on version 5.

My (cheap) provider does not give me the means to update to a later version of SQLite.

@DunklesKaltesNichts Your version 3.27.2 is also too old.

**Comment by DunklesKaltesNichts** [comment] 2023-11-11 06:15
@rikfleuren  this is shared hosting, there's nothing i can do about it.

**Comment by splitbrain** [comment] 2023-11-11 14:47
What PHP versions are you running?

**Comment by rikfleuren** [comment] 2023-11-12 20:13
@splitbrain I tried with PHP versions 7.4, 8.0, 8.1 and 8.2 (more precisely 8.2.10), before I noticed that all those versions uses an SQLite version that is too old for `ALTER TABLE DROP COLUMN`.

From `phpinfo()`, at 'PDO Driver for SQLite 3.x' I get: SQLite Library = 3.7.17.

Usually I install DokuWiki on servers I configure myself, but this is for someone with a cheap shared hosting provider.

I can imagine that you could provide the database in the "latest version" for new installs of the plugin, but then I would get this same problem with the next update. And the SQLite version that introduced the necessary support is from 2021, so that should have been installed already. I shall try asking the provider to do an SQLite update. But I can easily manage to run the DokuWiki on another server

**Comment by ocapito** [comment] 2024-03-06 16:09
I also get this error on Release 2024-02-06a "Kaos" (compatibility in the Plugin description is marked as unknown).
Im running it on some webspace provider on an apache server with PHP 8.2.16. No Idea how to find out which SQLite Version this runs on.

Deactivating the plugin makes the Error go away, when I reactivate it, the error comes back.

**Comment by ma44in** [comment] 2024-10-28 09:14
I would like to report, that we are hitting the same error with release 2024-02-06a "Kaos" and PHP 8.1.27 and unfortunately cannot use this helpful plugin.

Thanks in advance for your great work on dokuwiki :)

**Comment by annda** [comment] 2024-12-05 19:08
I am closing the issue because the error is caused by an outdated SQLite Library.  We do not intend to add backwards compatibility for stale OS packages (more than 3 years).

**Closed by annda** 2024-12-05 19:08 UTC
